### ISSUE TITLE
Why file extensions are jsx ? Its not React right ??

### ISSUE THREAD

**Issue by romanrokon** [GodotExplorer/ECMAScriptDemos#2]
I'm confused...

**Comment by Geequlim** [comment]
In godot engine a *Script* is treaded as a class extends from godot.Object. So only a script export a class that extends from godot.Object is a valid **godot script**.

The godot editor always tries to parse all files with valid script extension as a godot class. But most of our `.js` files in project are not aimmed to be used by Node so they don't extends from godot.Object. In godot side the script is not a *Script*.
Therefore, I have to sperate them to two resource type. Scripts that can be mounted to Node use `.jsx` extension, to avoid the editor constantly trying to parse the `.js` files into the classes.

**Why is JSX**
Because typescript can only compile files from `ts` to `js` and `tsx` to `jsx`.

**Comment by romanrokon** [comment]
Okay I got it.
